//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Xml.Serialization;

namespace Europass.Net.Model
{

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://europass.cedefop.europa.eu/Europass")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass", IsNullable = false)]
    public partial class SkillsPassport
    {

        private DocumentInfoType documentInfoField;

        private DocumentPreferencesType[] printingPreferencesField;

        private LearnerInfoType learnerInfoField;

        private AttachmentType[] attachmentListField;

        private CoverLetterType coverLetterField;

        private string localeField;


        public DocumentInfoType DocumentInfo
        {
            get
            {
                return this.documentInfoField;
            }
            set
            {
                this.documentInfoField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable = false)]
        public DocumentPreferencesType[] PrintingPreferences
        {
            get
            {
                return this.printingPreferencesField;
            }
            set
            {
                this.printingPreferencesField = value;
            }
        }


        public LearnerInfoType LearnerInfo
        {
            get
            {
                return this.learnerInfoField;
            }
            set
            {
                this.learnerInfoField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Attachment", IsNullable = false)]
        public AttachmentType[] AttachmentList
        {
            get
            {
                return this.attachmentListField;
            }
            set
            {
                this.attachmentListField = value;
            }
        }


        public CoverLetterType CoverLetter
        {
            get
            {
                return this.coverLetterField;
            }
            set
            {
                this.coverLetterField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class DocumentInfoType
    {

        private DocumentTypeType documentTypeField;

        private DocumentTypeType[] bundleField;

        private System.DateTime creationDateField;

        private System.DateTime lastUpdateDateField;

        private string xSDVersionField;

        private string generatorField;

        private string commentField;

        private string copyrightField;

        private bool europassLogoField;

        private bool europassLogoFieldSpecified;

        public DocumentInfoType()
        {
            this.copyrightField = "© European Communities | http://europass.cedefop.europa.eu";
        }


        public DocumentTypeType DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable = false)]
        public DocumentTypeType[] Bundle
        {
            get
            {
                return this.bundleField;
            }
            set
            {
                this.bundleField = value;
            }
        }


        public System.DateTime CreationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }


        public System.DateTime LastUpdateDate
        {
            get
            {
                return this.lastUpdateDateField;
            }
            set
            {
                this.lastUpdateDateField = value;
            }
        }


        public string XSDVersion
        {
            get
            {
                return this.xSDVersionField;
            }
            set
            {
                this.xSDVersionField = value;
            }
        }


        public string Generator
        {
            get
            {
                return this.generatorField;
            }
            set
            {
                this.generatorField = value;
            }
        }


        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }


        public string Copyright
        {
            get
            {
                return this.copyrightField;
            }
            set
            {
                this.copyrightField = value;
            }
        }


        public bool EuropassLogo
        {
            get
            {
                return this.europassLogoField;
            }
            set
            {
                this.europassLogoField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EuropassLogoSpecified
        {
            get
            {
                return this.europassLogoFieldSpecified;
            }
            set
            {
                this.europassLogoFieldSpecified = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public enum DocumentTypeType
    {


        ECV_ESP,


        ESP,


        ECV,


        ELP,


        ECL,


        EX,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class AddresseeType
    {

        private PersonNameType personNameField;

        private OccupationalFieldType positionField;

        private OrganisationType organisationField;


        public PersonNameType PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }


        public OccupationalFieldType Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }


        public OrganisationType Organisation
        {
            get
            {
                return this.organisationField;
            }
            set
            {
                this.organisationField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class PersonNameType
    {

        private PersonTitleLabelType titleField;

        private string firstNameField;

        private string surnameField;


        public PersonTitleLabelType Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }


        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }


        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class PersonTitleLabelType : LabelType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpeningSalutationSalutationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClosingSalutationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AchievementTypeLabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinguisticExperienceAreaType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeignLanguageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MotherLanguageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EducationalFieldType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EducationalLevelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinesSectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationalWebsiteUseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentationHeadingLabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HeadlineTypeLabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionTypeLabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OccupationalFieldType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenderLabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NationalityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstantMessagingUseLabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebsiteUseLabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelephoneUseLabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonTitleLabelType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LabelType
    {

        private string codeField;

        private string labelField;


        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }


        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class OpeningSalutationSalutationType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ClosingSalutationType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class AchievementTypeLabelType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LinguisticExperienceAreaType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ForeignLanguageType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class MotherLanguageType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public abstract partial class LanguageType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class EducationalFieldType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class EducationalLevelType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class BusinesSectorType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class OrganisationalWebsiteUseType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class DocumentationHeadingLabelType : LabelType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionTypeLabelType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class HeadlineTypeLabelType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class PositionTypeLabelType : HeadlineTypeLabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class OccupationalFieldType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class GenderLabelType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class NationalityType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class InstantMessagingUseLabelType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class WebsiteUseLabelType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class TelephoneUseLabelType : LabelType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class CountryType : LabelType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class OrganisationType
    {

        private string nameField;

        private OrganisationalContactInfoType contactInfoField;


        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }


        public OrganisationalContactInfoType ContactInfo
        {
            get
            {
                return this.contactInfoField;
            }
            set
            {
                this.contactInfoField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class OrganisationalContactInfoType
    {

        private ContactAddressType addressField;

        private OrganisationalWebsiteType websiteField;


        public ContactAddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }


        public OrganisationalWebsiteType Website
        {
            get
            {
                return this.websiteField;
            }
            set
            {
                this.websiteField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ContactAddressType : ContactMethodType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactEmailType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationalWebsiteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactAddressType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstantMessagingType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebsiteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelephoneType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public abstract partial class ContactMethodType
    {

        private object contactField;

        private LabelType useField;


        public object Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }


        public LabelType Use
        {
            get
            {
                return this.useField;
            }
            set
            {
                this.useField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ContactEmailType : ContactMethodType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class OrganisationalWebsiteType : ContactMethodType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class InstantMessagingType : ContactMethodType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class WebsiteType : ContactMethodType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class TelephoneType : ContactMethodType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class EmployerType : OrganisationType
    {

        private BusinesSectorType sectorField;


        public BusinesSectorType Sector
        {
            get
            {
                return this.sectorField;
            }
            set
            {
                this.sectorField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class CoverLetterType
    {

        private AddresseeType addresseeField;

        private LetterType letterField;

        private GenericDocumentationType documentationField;


        public AddresseeType Addressee
        {
            get
            {
                return this.addresseeField;
            }
            set
            {
                this.addresseeField = value;
            }
        }


        public LetterType Letter
        {
            get
            {
                return this.letterField;
            }
            set
            {
                this.letterField = value;
            }
        }


        public GenericDocumentationType Documentation
        {
            get
            {
                return this.documentationField;
            }
            set
            {
                this.documentationField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LetterType
    {

        private LetterLocalisationType localisationField;

        private string subjectLineField;

        private OpeningSalutationType openingSalutationField;

        private BodyType bodyField;

        private ClosingSalutationType closingSalutationField;


        public LetterLocalisationType Localisation
        {
            get
            {
                return this.localisationField;
            }
            set
            {
                this.localisationField = value;
            }
        }


        public string SubjectLine
        {
            get
            {
                return this.subjectLineField;
            }
            set
            {
                this.subjectLineField = value;
            }
        }


        public OpeningSalutationType OpeningSalutation
        {
            get
            {
                return this.openingSalutationField;
            }
            set
            {
                this.openingSalutationField = value;
            }
        }


        public BodyType Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }


        public ClosingSalutationType ClosingSalutation
        {
            get
            {
                return this.closingSalutationField;
            }
            set
            {
                this.closingSalutationField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LetterLocalisationType
    {

        private DateType dateField;

        private LocalisationPlaceType placeField;


        public DateType Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }


        public LocalisationPlaceType Place
        {
            get
            {
                return this.placeField;
            }
            set
            {
                this.placeField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class DateType
    {
        private string yearField;

        private string monthField;

        private string dayField;


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LocalisationPlaceType : AddressInfoType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocalisationPlaceType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class AddressInfoType
    {

        private string addressLineField;

        private string addressLine2Field;

        private string postalCodeField;

        private string municipalityField;

        private CountryType countryField;


        public string AddressLine
        {
            get
            {
                return this.addressLineField;
            }
            set
            {
                this.addressLineField = value;
            }
        }


        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }


        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }


        public string Municipality
        {
            get
            {
                return this.municipalityField;
            }
            set
            {
                this.municipalityField = value;
            }
        }


        public CountryType Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class OpeningSalutationType
    {

        private OpeningSalutationSalutationType salutationField;

        private PersonNameType personNameField;


        public OpeningSalutationSalutationType Salutation
        {
            get
            {
                return this.salutationField;
            }
            set
            {
                this.salutationField = value;
            }
        }


        public PersonNameType PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class BodyType
    {

        private string openingField;

        private string mainBodyField;

        private string closingField;


        public string Opening
        {
            get
            {
                return this.openingField;
            }
            set
            {
                this.openingField = value;
            }
        }


        public string MainBody
        {
            get
            {
                return this.mainBodyField;
            }
            set
            {
                this.mainBodyField = value;
            }
        }


        public string Closing
        {
            get
            {
                return this.closingField;
            }
            set
            {
                this.closingField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class GenericDocumentationType
    {

        private DocumentationHeadingLabelType headingField;

        private EuropassDocumentReferenceType[] interDocumentField;

        private InternalReferenceType[] intraDocumentField;

        private ExternalReferenceType[] extraDocumentField;


        public DocumentationHeadingLabelType Heading
        {
            get
            {
                return this.headingField;
            }
            set
            {
                this.headingField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("ReferencedDocument", IsNullable = false)]
        public EuropassDocumentReferenceType[] InterDocument
        {
            get
            {
                return this.interDocumentField;
            }
            set
            {
                this.interDocumentField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("ReferenceTo", IsNullable = false)]
        public InternalReferenceType[] IntraDocument
        {
            get
            {
                return this.intraDocumentField;
            }
            set
            {
                this.intraDocumentField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("ReferencedResource", IsNullable = false)]
        public ExternalReferenceType[] ExtraDocument
        {
            get
            {
                return this.extraDocumentField;
            }
            set
            {
                this.extraDocumentField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class EuropassDocumentReferenceType
    {

        private DocumentTypeType refField;

        private bool refFieldSpecified;


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentTypeType @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool refSpecified
        {
            get
            {
                return this.refFieldSpecified;
            }
            set
            {
                this.refFieldSpecified = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class InternalReferenceType
    {

        private string idrefField;


        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string idref
        {
            get
            {
                return this.idrefField;
            }
            set
            {
                this.idrefField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ExternalReferenceType
    {

        private string descriptionField;

        private string hrefField;


        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class SkillSetType
    {

        private LinguisticSkillType linguisticField;

        private GenericSkillType communicationField;

        private GenericSkillType organisationalField;

        private GenericSkillType jobRelatedField;

        private ComputerSkillType computerField;

        private DrivingSkillType drivingField;

        private GenericSkillType otherField;


        public LinguisticSkillType Linguistic
        {
            get
            {
                return this.linguisticField;
            }
            set
            {
                this.linguisticField = value;
            }
        }


        public GenericSkillType Communication
        {
            get
            {
                return this.communicationField;
            }
            set
            {
                this.communicationField = value;
            }
        }


        public GenericSkillType Organisational
        {
            get
            {
                return this.organisationalField;
            }
            set
            {
                this.organisationalField = value;
            }
        }


        public GenericSkillType JobRelated
        {
            get
            {
                return this.jobRelatedField;
            }
            set
            {
                this.jobRelatedField = value;
            }
        }


        public ComputerSkillType Computer
        {
            get
            {
                return this.computerField;
            }
            set
            {
                this.computerField = value;
            }
        }


        public DrivingSkillType Driving
        {
            get
            {
                return this.drivingField;
            }
            set
            {
                this.drivingField = value;
            }
        }


        public GenericSkillType Other
        {
            get
            {
                return this.otherField;
            }
            set
            {
                this.otherField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LinguisticSkillType
    {

        private MotherTongueSkillType[] motherTongueListField;

        private ForeignLanguageSkillType[] foreignLanguageListField;


        [System.Xml.Serialization.XmlArrayItemAttribute("MotherTongue", IsNullable = false)]
        public MotherTongueSkillType[] MotherTongueList
        {
            get
            {
                return this.motherTongueListField;
            }
            set
            {
                this.motherTongueListField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("ForeignLanguage", IsNullable = false)]
        public ForeignLanguageSkillType[] ForeignLanguageList
        {
            get
            {
                return this.foreignLanguageListField;
            }
            set
            {
                this.foreignLanguageListField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class MotherTongueSkillType : SkillType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeignLanguageSkillType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MotherTongueSkillType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComputerSkillType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DrivingSkillType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericSkillType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public abstract partial class SkillType
    {

        private object descriptionField;

        private object proficiencyLevelField;

        private object[] acquiredDuringField;

        private CertificateType[] verifiedByField;

        private InternalReferenceType[] documentationField;


        public object Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }


        public object ProficiencyLevel
        {
            get
            {
                return this.proficiencyLevelField;
            }
            set
            {
                this.proficiencyLevelField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Experience", IsNullable = false)]
        public object[] AcquiredDuring
        {
            get
            {
                return this.acquiredDuringField;
            }
            set
            {
                this.acquiredDuringField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Certificate", IsNullable = false)]
        public CertificateType[] VerifiedBy
        {
            get
            {
                return this.verifiedByField;
            }
            set
            {
                this.verifiedByField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("ReferenceTo", IsNullable = false)]
        public InternalReferenceType[] Documentation
        {
            get
            {
                return this.documentationField;
            }
            set
            {
                this.documentationField = value;
            }
        }
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinguisticCertificateType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComputerCertificateType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class CertificateType
    {

        private string titleField;

        private string awardingBodyField;

        private DateType dateField;

        private object levelField;


        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }


        public string AwardingBody
        {
            get
            {
                return this.awardingBodyField;
            }
            set
            {
                this.awardingBodyField = value;
            }
        }


        public DateType Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }


        public object Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LinguisticCertificateType : CertificateType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ComputerCertificateType : CertificateType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ForeignLanguageSkillType : SkillType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ComputerSkillType : SkillType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class DrivingSkillType : SkillType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class GenericSkillType : SkillType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class AchievementType
    {

        private AchievementTypeLabelType titleField;

        private string descriptionField;

        private InternalReferenceType[] documentationField;


        public AchievementTypeLabelType Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }


        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("ReferenceTo", IsNullable = false)]
        public InternalReferenceType[] Documentation
        {
            get
            {
                return this.documentationField;
            }
            set
            {
                this.documentationField = value;
            }
        }
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinguisticCertificateListType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComputerCertificateListType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class CertificateListType
    {

        private CertificateType[] certificateField;


        [System.Xml.Serialization.XmlElementAttribute("Certificate")]
        public CertificateType[] Certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LinguisticCertificateListType : CertificateListType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ComputerCertificateListType : CertificateListType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EducationalExperienceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkExperienceType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ExperienceType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class EducationalExperienceType : ExperienceType
    {
        private PeriodType periodField;

        private string titleField;

        private string activitiesField;

        private OrganisationType organisationField;

        private EducationalLevelType levelField;

        private EducationalFieldType fieldField;

        public PeriodType Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }

        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }


        public string Activities
        {
            get
            {
                return this.activitiesField;
            }
            set
            {
                this.activitiesField = value;
            }
        }


        public OrganisationType Organisation
        {
            get
            {
                return this.organisationField;
            }
            set
            {
                this.organisationField = value;
            }
        }


        public EducationalLevelType Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }


        public EducationalFieldType Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class WorkExperienceType : ExperienceType
    {
        private PeriodType periodField;

        private OccupationalFieldType positionField;

        private string activitiesField;

        private EmployerType employerField;


        public PeriodType Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }

        public OccupationalFieldType Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }


        public string Activities
        {
            get
            {
                return this.activitiesField;
            }
            set
            {
                this.activitiesField = value;
            }
        }


        public EmployerType Employer
        {
            get
            {
                return this.employerField;
            }
            set
            {
                this.employerField = value;
            }
        }
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinguisticExperienceListType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class AbstractExperienceListType
    {

        private object[] experienceField;


        [System.Xml.Serialization.XmlElementAttribute("Experience")]
        public object[] Experience
        {
            get
            {
                return this.experienceField;
            }
            set
            {
                this.experienceField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LinguisticExperienceListType : AbstractExperienceListType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class HeadlineType
    {

        private HeadlineTypeLabelType typeField;

        private OccupationalFieldType descriptionField;


        public HeadlineTypeLabelType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }


        public OccupationalFieldType Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class PositionType : HeadlineType
    {
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhotoDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SignatureDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachmentType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class FileDataType
    {

        private string nameField;

        private MimeTypeEnumeration mimeTypeField;

        private byte[] dataField;

        private MetadataListTypeMetadata[] metadataListField;


        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }


        public MimeTypeEnumeration MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Metadata", IsNullable = false)]
        public MetadataListTypeMetadata[] MetadataList
        {
            get
            {
                return this.metadataListField;
            }
            set
            {
                this.metadataListField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public enum MimeTypeEnumeration
    {


        [System.Xml.Serialization.XmlEnumAttribute("image/jpeg")]
        imagejpeg,


        [System.Xml.Serialization.XmlEnumAttribute("image/pjpeg")]
        imagepjpeg,


        [System.Xml.Serialization.XmlEnumAttribute("image/png")]
        imagepng,


        [System.Xml.Serialization.XmlEnumAttribute("image/x-png")]
        imagexpng,


        [System.Xml.Serialization.XmlEnumAttribute("application/pdf")]
        applicationpdf,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class MetadataListTypeMetadata
    {

        private string keyField;

        private string valueField;


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SignatureDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class PhotoDataType : FileDataType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class SignatureDataType : PhotoDataType
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class AttachmentType : FileDataType
    {

        private string descriptionField;

        private string idField;


        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class DemographicsType
    {

        private DateType birthdateField;

        private GenderLabelType genderField;

        private NationalityType[] nationalityListField;


        public DateType Birthdate
        {
            get
            {
                return this.birthdateField;
            }
            set
            {
                this.birthdateField = value;
            }
        }


        public GenderLabelType Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Nationality", IsNullable = false)]
        public NationalityType[] NationalityList
        {
            get
            {
                return this.nationalityListField;
            }
            set
            {
                this.nationalityListField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class PeriodType
    {

        private DateType fromField;

        private DateType toField;

        private bool currentField;

        private bool currentFieldSpecified;

        private string durationField;

        private string durationEquivalentField;


        public DateType From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }


        public DateType To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }


        public bool Current
        {
            get
            {
                return this.currentField;
            }
            set
            {
                this.currentField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrentSpecified
        {
            get
            {
                return this.currentFieldSpecified;
            }
            set
            {
                this.currentFieldSpecified = value;
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }


        public string DurationEquivalent
        {
            get
            {
                return this.durationEquivalentField;
            }
            set
            {
                this.durationEquivalentField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class ContactInfoType
    {

        private ContactAddressType addressField;

        private ContactEmailType emailField;

        private TelephoneType[] telephoneListField;

        private WebsiteType[] websiteListField;

        private InstantMessagingType[] instantMessagingListField;

        private ContactMethodType[] contactMethodListField;


        public ContactAddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }


        public ContactEmailType Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Telephone", IsNullable = false)]
        public TelephoneType[] TelephoneList
        {
            get
            {
                return this.telephoneListField;
            }
            set
            {
                this.telephoneListField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Website", IsNullable = false)]
        public WebsiteType[] WebsiteList
        {
            get
            {
                return this.websiteListField;
            }
            set
            {
                this.websiteListField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("InstantMessaging", IsNullable = false)]
        public InstantMessagingType[] InstantMessagingList
        {
            get
            {
                return this.instantMessagingListField;
            }
            set
            {
                this.instantMessagingListField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("ContactMethod", IsNullable = false)]
        public ContactMethodType[] ContactMethodList
        {
            get
            {
                return this.contactMethodListField;
            }
            set
            {
                this.contactMethodListField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class IdentificationType
    {

        private PersonNameType personNameField;

        private ContactInfoType contactInfoField;

        private DemographicsType demographicsField;

        private PhotoDataType photoField;

        private SignatureDataType signatureField;


        public PersonNameType PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }


        public ContactInfoType ContactInfo
        {
            get
            {
                return this.contactInfoField;
            }
            set
            {
                this.contactInfoField = value;
            }
        }


        public DemographicsType Demographics
        {
            get
            {
                return this.demographicsField;
            }
            set
            {
                this.demographicsField = value;
            }
        }


        public PhotoDataType Photo
        {
            get
            {
                return this.photoField;
            }
            set
            {
                this.photoField = value;
            }
        }


        public SignatureDataType Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class LearnerInfoType
    {

        private IdentificationType identificationField;

        private HeadlineType headlineField;

        private WorkExperienceType[] workExperienceListField;

        private EducationalExperienceType[] educationListField;

        private SkillSetType skillsField;

        private AchievementType[] achievementListField;

        private InternalReferenceType[] documentationField;


        public IdentificationType Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }


        public HeadlineType Headline
        {
            get
            {
                return this.headlineField;
            }
            set
            {
                this.headlineField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("WorkExperience", IsNullable = false)]
        public WorkExperienceType[] WorkExperienceList
        {
            get
            {
                return this.workExperienceListField;
            }
            set
            {
                this.workExperienceListField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Education", IsNullable = false)]
        public EducationalExperienceType[] EducationList
        {
            get
            {
                return this.educationListField;
            }
            set
            {
                this.educationListField = value;
            }
        }


        public SkillSetType Skills
        {
            get
            {
                return this.skillsField;
            }
            set
            {
                this.skillsField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("Achievement", IsNullable = false)]
        public AchievementType[] AchievementList
        {
            get
            {
                return this.achievementListField;
            }
            set
            {
                this.achievementListField = value;
            }
        }


        [System.Xml.Serialization.XmlArrayItemAttribute("ReferenceTo", IsNullable = false)]
        public InternalReferenceType[] Documentation
        {
            get
            {
                return this.documentationField;
            }
            set
            {
                this.documentationField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class DocumentPreferencesType
    {

        private DocumentPreferencesTypeField[] fieldField;

        private DocumentTypeEnumeration typeField;


        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public DocumentPreferencesTypeField[] Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentTypeEnumeration type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public partial class DocumentPreferencesTypeField
    {

        private string nameField;

        private bool showField;

        private bool showFieldSpecified;

        private string formatField;

        private OrderNames orderField;

        private bool orderFieldSpecified;

        private PositionNames positionField;

        private bool positionFieldSpecified;

        private bool justifyField;

        private bool justifyFieldSpecified;


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool show
        {
            get
            {
                return this.showField;
            }
            set
            {
                this.showField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showSpecified
        {
            get
            {
                return this.showFieldSpecified;
            }
            set
            {
                this.showFieldSpecified = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OrderNames order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderSpecified
        {
            get
            {
                return this.orderFieldSpecified;
            }
            set
            {
                this.orderFieldSpecified = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PositionNames position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool justify
        {
            get
            {
                return this.justifyField;
            }
            set
            {
                this.justifyField = value;
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool justifySpecified
        {
            get
            {
                return this.justifyFieldSpecified;
            }
            set
            {
                this.justifyFieldSpecified = value;
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public enum OrderNames
    {


        [System.Xml.Serialization.XmlEnumAttribute("FirstName Surname")]
        FirstNameSurname,


        [System.Xml.Serialization.XmlEnumAttribute("Surname FirstName")]
        SurnameFirstName,


        [System.Xml.Serialization.XmlEnumAttribute("Title FirstName Surname")]
        TitleFirstNameSurname,


        [System.Xml.Serialization.XmlEnumAttribute("Title Surname FirstName")]
        TitleSurnameFirstName,


        [System.Xml.Serialization.XmlEnumAttribute("FirstName Surname Title")]
        FirstNameSurnameTitle,


        [System.Xml.Serialization.XmlEnumAttribute("Surname FirstName Title")]
        SurnameFirstNameTitle,


        [System.Xml.Serialization.XmlEnumAttribute("Identification Headline WorkExperience Education Skills Achievement ReferenceTo")]
        IdentificationHeadlineWorkExperienceEducationSkillsAchievementReferenceTo,


        [System.Xml.Serialization.XmlEnumAttribute("Identification Headline Education WorkExperience Skills Achievement ReferenceTo")]
        IdentificationHeadlineEducationWorkExperienceSkillsAchievementReferenceTo,


        [System.Xml.Serialization.XmlEnumAttribute("Identification Skills ReferenceTo")]
        IdentificationSkillsReferenceTo,


        [System.Xml.Serialization.XmlEnumAttribute("Addressee Letter.SubjectLine Letter.OpeningSalutation Letter.Body Letter.Localisa" +
            "tion Letter.ClosingSalutation")]
        AddresseeLetterSubjectLineLetterOpeningSalutationLetterBodyLetterLocalisationLetterClosingSalutation,


        [System.Xml.Serialization.XmlEnumAttribute("Letter.SubjectLine Addressee Letter.OpeningSalutation Letter.Body Letter.Localisa" +
            "tion Letter.ClosingSalutation")]
        LetterSubjectLineAddresseeLetterOpeningSalutationLetterBodyLetterLocalisationLetterClosingSalutation,


        [System.Xml.Serialization.XmlEnumAttribute("Letter.Localisation Addressee Letter.SubjectLine Letter.OpeningSalutation Letter." +
            "Body Letter.ClosingSalutation")]
        LetterLocalisationAddresseeLetterSubjectLineLetterOpeningSalutationLetterBodyLetterClosingSalutation,


        [System.Xml.Serialization.XmlEnumAttribute("Letter.SubjectLine Addressee Letter.Localisation Letter.OpeningSalutation Letter." +
            "Body Letter.ClosingSalutation")]
        LetterSubjectLineAddresseeLetterLocalisationLetterOpeningSalutationLetterBodyLetterClosingSalutation,


        [System.Xml.Serialization.XmlEnumAttribute("Letter.Localisation Letter.SubjectLine Addressee Letter.OpeningSalutation Letter." +
            "Body Letter.ClosingSalutation")]
        LetterLocalisationLetterSubjectLineAddresseeLetterOpeningSalutationLetterBodyLetterClosingSalutation,


        [System.Xml.Serialization.XmlEnumAttribute("Addressee Letter.Localisation Letter.SubjectLine Letter.OpeningSalutation Letter." +
            "Body Letter.ClosingSalutation")]
        AddresseeLetterLocalisationLetterSubjectLineLetterOpeningSalutationLetterBodyLetterClosingSalutation,


        [System.Xml.Serialization.XmlEnumAttribute("Addressee Letter.SubjectLine Letter.Localisation Letter.OpeningSalutation Letter." +
            "Body Letter.ClosingSalutation")]
        AddresseeLetterSubjectLineLetterLocalisationLetterOpeningSalutationLetterBodyLetterClosingSalutation,


        [System.Xml.Serialization.XmlEnumAttribute("Date Place")]
        DatePlace,


        [System.Xml.Serialization.XmlEnumAttribute("Place Date")]
        PlaceDate,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public enum PositionNames
    {


        [System.Xml.Serialization.XmlEnumAttribute("left-align")]
        leftalign,


        [System.Xml.Serialization.XmlEnumAttribute("right-align")]
        rightalign,


        [System.Xml.Serialization.XmlEnumAttribute("middle-align")]
        middlealign,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://europass.cedefop.europa.eu/Europass")]
    public enum DocumentTypeEnumeration
    {


        ECV,


        ELP,


        ECL,
    }
}